<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE DATABASE_DIGIT2[
<!ELEMENT DATABASE_DIGIT2 (RECORD*)>
<!ELEMENT RECORD (Tag_1?, Tag_2?, Tag_3?, Tag_4?, Tag_5*, Tag_6?, Tag_7?, Tag_8?, Tag_9*, Tag_10?, Tag_11?, Tag_12?)>
<!ELEMENT Tag_1 (#PCDATA)*>
<!ELEMENT Tag_2 (#PCDATA)*>
<!ELEMENT Tag_3 (#PCDATA)*>
<!ELEMENT Tag_4 (#PCDATA)*>
<!ELEMENT Tag_5 (#PCDATA)*>
<!ELEMENT Tag_6 (#PCDATA)*>
<!ELEMENT Tag_7 (#PCDATA)*>
<!ELEMENT Tag_8 (#PCDATA)*>
<!ELEMENT Tag_9 (#PCDATA)*>
<!ELEMENT Tag_10 (#PCDATA)*>
<!ELEMENT Tag_11 (#PCDATA)*>
<!ELEMENT Tag_12 (#PCDATA)*>
]>
<DATABASE_DIGIT2>
<RECORD>
<Tag_1>1.1. </Tag_1>
<Tag_2>ESTADISTICAS. </Tag_2>
<Tag_3>BANCOS, SEGUROS Y FINANZAS. </Tag_3>
<Tag_4>BOLETIN DE ESTADISTICA. </Tag_4>
<Tag_5>SUPERINTENDENCIA DE BANCOS. </Tag_5>
<Tag_6>GUATEMALA. </Tag_6>
<Tag_7>MARZO 2008. </Tag_7>
<Tag_8>LAS CIFRAS QUE SE PRESENTAN NO HAN SIDO AUDITADAS Y TIENEN COMO FUENTE LA INFORMACION CONTABLE RECIBIDA DE LAS ENTIDADES FINANCIERAS, POR LO QUE SU VERACIDAD Y EXACTITUD, ASI COMO SUS DIFERENCIAS, SON RESPONSABILIDAD DE LAS ENTIDADES REMITENTES. </Tag_8>
<Tag_9>SISTEMA BANCARIO. </Tag_9>
<Tag_9>CASAS DE CAMBIO. </Tag_9>
<Tag_10>3. </Tag_10>
<Tag_11>1. </Tag_11>
<Tag_12>06/06/2008. </Tag_12>
</RECORD>
<RECORD>
<Tag_1>1.2. </Tag_1>
<Tag_2>ESTADISTICAS. </Tag_2>
<Tag_3>BANCOS, SEGUROS Y FINANZAS. </Tag_3>
<Tag_4>BOLETIN ANUAL DE ESTADISTICAS. </Tag_4>
<Tag_5>SUPERINTENDENCIA DE BANCOS. </Tag_5>
<Tag_6>GUATEMALA. </Tag_6>
<Tag_7>AÑO 2007. </Tag_7>
<Tag_8>LAS CIFRAS QUE SE PRESENTAN NO HAN SIDO AUDITADAS Y TIENEN COMO FUENTE LA INFORMACION CONTABLE RECIBIDA DE LAS ENTIDADES FINANCIERAS, POR LO QUE SU VERACIDAD Y EXACTITUD, ASI COMO SUS DEFICIENCIAS, SON RESPONSABILIDAD DE LAS ENTIDADES REMITENTES. </Tag_8>
<Tag_9>SISTEMA BANCARIO. </Tag_9>
<Tag_9>BANCOS EXTRANJEROS. </Tag_9>
<Tag_10>3. </Tag_10>
<Tag_11>1. </Tag_11>
<Tag_12>06/06/2008. </Tag_12>
</RECORD>
<RECORD>
<Tag_1>1.3. </Tag_1>
<Tag_2>ESTADISTICAS. </Tag_2>
<Tag_3>BANCOS, SEGUROS Y FINANZAS. </Tag_3>
<Tag_4>BOLETIN DE ESTADISTICAS. </Tag_4>
<Tag_5>SUPERINTENDENCIA DE BANCOS. </Tag_5>
<Tag_6>GUATEMALA. </Tag_6>
<Tag_7>MAYO 2007. </Tag_7>
<Tag_8>LAS CIFRAS QUE SE PRESENTAN NO HAN SIDO AUDITADAS Y TIENEN COMO FUENTE LA INFORMACION CONTABLE RECIBIDA DE LAS ENTIDADES FINANCIERAS, POR LO QUE SU VERACIDAD Y EXACTITUD, ASI COMO SUS DEFICIENCIAS, SON RESPONSABILIDAD DE LAS ENTIDADES REMITENTES. </Tag_8>
<Tag_9>SISTEMA BANCARIO. </Tag_9>
<Tag_9>SOCIEDADES FINANCIERAS PRIVADAS. </Tag_9>
<Tag_10>3. </Tag_10>
<Tag_11>1. </Tag_11>
<Tag_12>06/06/2008. </Tag_12>
</RECORD>
<RECORD>
<Tag_1>1.4. </Tag_1>
<Tag_2>ESTADISTICAS. </Tag_2>
<Tag_3>BANCOS, SEGUROS Y FINANZAS. </Tag_3>
<Tag_4>BOLETIN ANUAL DE ESTADISTICAS. </Tag_4>
<Tag_5>SUPERINTENDENCIA DE BANCOS. </Tag_5>
<Tag_6>GUATEMALA. </Tag_6>
<Tag_7>AÑO 2006. </Tag_7>
<Tag_8>LAS CIFRAS QUE SE PRESENTAN NO HAN SIDO AUDITADAS Y TIENEN COMO FUENTE LA INFORMACION CONTABLE RECIBIDA DE LAS ENTIDADES FINANCIERAS, POR LO QUE SU VERACIDAD Y EXACTITUD, ASI COMO SUS DEFICIENCIAS, SON RESPONSABILIDAD DE LAS ENTIDADES REMITENTES. </Tag_8>
<Tag_9>INFORMACION GENERAL. </Tag_9>
<Tag_9>EMPRESAS DE SEGUROS INFORMACION FINANCIERA. </Tag_9>
<Tag_10>3. </Tag_10>
<Tag_11>1. </Tag_11>
<Tag_12>06/06/2008. </Tag_12>
</RECORD>
<RECORD>
<Tag_1>1.5. </Tag_1>
<Tag_2>ESTADISTICAS. </Tag_2>
<Tag_3>BANCOS, SEGUROS Y FINANZAS. </Tag_3>
<Tag_4>BOLETIN TRIMESTRAL DE ESTADISTICA. </Tag_4>
<Tag_5>SUPERINTENDENCIA DE BANCOS. </Tag_5>
<Tag_6>GUATEMALA. </Tag_6>
<Tag_7>MARZO 2007. </Tag_7>
<Tag_8>LAS CIFRAS QUE SE PRESENTAN NO HAN SIDO AUDITADAS Y TIENEN COMO FUENTE LA INFORMACION CONTABLE RECIBIDA DE LAS ENTIDADES FINANCIERAS, POR LO QUE SU VERACIDAD Y EXACTITUD, ASI COMO SUS DEFICIENCIAS, SON RESPONSABILIDAD DE LAS ENTIDADES REMITENTES. </Tag_8>
<Tag_9>INFORMACION GENERAL. </Tag_9>
<Tag_9>EMPRESAS DE FIANZAS. </Tag_9>
<Tag_10>3. </Tag_10>
<Tag_11>1. </Tag_11>
<Tag_12>06/06/2008. </Tag_12>
</RECORD>
<RECORD>
<Tag_1>1.6. </Tag_1>
<Tag_2>ESTADISTICAS. </Tag_2>
<Tag_3>BANCOS, SEGUROS Y FINANZAS. </Tag_3>
<Tag_4>BOLETIN ANUAL DE ESTADISTICA. </Tag_4>
<Tag_5>SUPERINTENDENCIA DE BANCOS. </Tag_5>
<Tag_6>GUATEMALA. </Tag_6>
<Tag_7>AÑO 2006. </Tag_7>
<Tag_8>LAS CIFRAS QUE SE PRESENTAN NO HAN SIDO AUDITADAS Y TIENEN COMO FUENTE LA INFORMACION CONTABLE RECIBIDA DE LAS ENTIDADES FINANCIERAS, POR LO QUE SU VERACIDAD Y EXACTITUD, ASI COMO SUS DEFICIENCIAS, SON RESPONSABILIDAD DE LAS ENTIDADES REMITENTES. </Tag_8>
<Tag_9>INFORMACION GENERAL. </Tag_9>
<Tag_9>EMPRESAS DE SEGUROS INFORMACION NO FINANCIERA. </Tag_9>
<Tag_10>3. </Tag_10>
<Tag_11>1. </Tag_11>
<Tag_12>06/06/2008. </Tag_12>
</RECORD>
<RECORD>
<Tag_1>1.7. </Tag_1>
<Tag_2>ESTADISTICAS. </Tag_2>
<Tag_3>BANCOS, SEGUROS Y FINANZAS. </Tag_3>
<Tag_4>BOLETIN TRIMESTRAL DE ESTADISTICAS. </Tag_4>
<Tag_5>SUPERINTENDENCIA DE BANCOS. </Tag_5>
<Tag_6>GUATEMALA. </Tag_6>
<Tag_7>JUNIO 2007. </Tag_7>
<Tag_8>LAS CIFRAS QUE SE PRESENTAN NO HAN SIDO AUDITADAS Y TIENEN COMO FUENTE LA INFORMACION CONTABLE RECIBIDA DE LAS ENTIDADES FINANCIERAS, POR LO QUE SU VERACIDAD Y EXACTITUD, ASI COMO SUS DEFICIENCIAS, SON RESPONSABILIDAD DE LAS ENTIDADES REMITENTES. </Tag_8>
<Tag_9>EMPRESAS DE SEGUROS. </Tag_9>
<Tag_9>EMPRESAS DE FIANZAS. </Tag_9>
<Tag_10>3. </Tag_10>
<Tag_11>1. </Tag_11>
<Tag_12>06/06/2008. </Tag_12>
</RECORD>
<RECORD>
<Tag_1>1.8. </Tag_1>
<Tag_2>ESTADISTICAS. </Tag_2>
<Tag_3>BANCOS, SEGUROS Y FINANZAS. </Tag_3>
<Tag_4>BOLETIN DE ESTADISTICAS. </Tag_4>
<Tag_5>SUPERINTENDENCIA DE BANCOS. </Tag_5>
<Tag_6>GUATEMALA. </Tag_6>
<Tag_7>JUNIO 2007. </Tag_7>
<Tag_8>LAS CIFRAS QUE SE PRESENTAN NO HAN SIDO AUDITADAS Y TIENEN COMO FUENTE LA INFORMACION CONTABLE RECIBIDA DE LAS ENTIDADES FINANCIERAS, POR LO QUE SU VERACIDAD Y EXACTITUD, ASI COMO SUS DEFICIENCIAS, SON RESPONSABILIDAD DE LAS ENTIDADES REMITENTES. </Tag_8>
<Tag_9>SISTEMA BANCARIO. </Tag_9>
<Tag_9>SOCIEDADES FINANCIERAS PRIVADAS. </Tag_9>
<Tag_10>3. </Tag_10>
<Tag_11>1. </Tag_11>
<Tag_12>06/06/2008. </Tag_12>
</RECORD>
<RECORD>
<Tag_1>1.9. </Tag_1>
<Tag_2>ESTADISTICAS. </Tag_2>
<Tag_3>BANCOS, SEGUROS Y FINANZAS. </Tag_3>
<Tag_4>BOLETIN TRIMESTRAL DE ESTADISTICA. </Tag_4>
<Tag_5>SUPERINTENDENCIA DE BANCOS. </Tag_5>
<Tag_6>GUATEMALA. </Tag_6>
<Tag_7>MARZO 2007. </Tag_7>
<Tag_8>LAS CIFRAS QUE SE PRESENTAN NO HAN SIDO AUDITADAS Y TIENEN COMO FUENTE LA INFORMACION CONTABLE RECIBIDA DE LAS ENTIDADES FINANCIERAS, POR LO QUE SU VERACIDAD Y EXACTITUD, ASI COMO SUS DEFICIENCIAS, SON RESPONSABILIDAD DE LAS ENTIDADES REMITENTES. </Tag_8>
<Tag_9>EMPRESAS DE SEGUROS. </Tag_9>
<Tag_9>EMPRESAS DE FIANZAS. </Tag_9>
<Tag_10>3. </Tag_10>
<Tag_11>1. </Tag_11>
<Tag_12>06/06/2008. </Tag_12>
</RECORD>
<RECORD>
<Tag_1>1.10. </Tag_1>
<Tag_2>ESTADISTICAS. </Tag_2>
<Tag_3>BANCOS, SEGUROS Y FINANZAS. </Tag_3>
<Tag_4>BOLETIN DE ESTADISTICAS. </Tag_4>
<Tag_5>SUPERINTENDENCIA DE BANCOS. </Tag_5>
<Tag_6>GUATEMALA. </Tag_6>
<Tag_7>MAYO 2007. </Tag_7>
<Tag_8>LAS CIFRAS QUE SE PRESENTAN NO HAN SIDO AUDITADAS Y TIENEN COMO FUENTE LA INFORMACION CONTABLE RECIBIDA DE LAS ENTIDADES FINANCIERAS, POR LO QUE SU VERACIDAD Y EXACTITUD, ASI COMO SUS DEFICIENCIAS, SON RESPONSABILIDAD DE LAS ENTIDADES REMITENTES. </Tag_8>
<Tag_9>SISTEMA BANCARIO. </Tag_9>
<Tag_9>SOCIEDADES FINANCIERAS PRIVADAS. </Tag_9>
<Tag_10>3. </Tag_10>
<Tag_11>1. </Tag_11>
<Tag_12>06/06/2008. </Tag_12>
</RECORD>
<RECORD>
<Tag_1>1.11. </Tag_1>
<Tag_2>ESTADISTICAS. </Tag_2>
<Tag_3>BANCOS, SEGUROS Y FINANZAS. </Tag_3>
<Tag_4>BOLETIN TRIMESTRAL DE ESTADISTICAS. </Tag_4>
<Tag_5>SUPERINTENDENCIA DE BANCOS. </Tag_5>
<Tag_6>GUATEMALA. </Tag_6>
<Tag_7>JUNIO 2007. </Tag_7>
<Tag_8>LAS CIFRAS QUE SE PRESENTAN NO HAN SIDO AUDITADAS Y TIENEN COMO FUENTE LA INFORMACION CONTABLE RECIBIDA DE LAS ENTIDADES FINANCIERAS, POR LO QUE SU VERACIDAD Y EXACTITUD , ASI COMO SUS DEFICIENCIAS, SON RESPONSABILIDAD DE LAS ENTIDADES REMITENTES. </Tag_8>
<Tag_9>EMPRESAS DE SEGUROS. </Tag_9>
<Tag_9>EMPRESAS DE FIANZAS. </Tag_9>
<Tag_10>3. </Tag_10>
<Tag_11>1. </Tag_11>
<Tag_12>06/06/2008. </Tag_12>
</RECORD>
<RECORD>
<Tag_1>1.12. </Tag_1>
<Tag_2>ESTADISTICAS. </Tag_2>
<Tag_3>BANCOS, SEGUROS Y FINANZAS. </Tag_3>
<Tag_4>BOLETIN DE ESTADISTICAS. </Tag_4>
<Tag_5>SUPERINTENDENCIA DE BANCOS. </Tag_5>
<Tag_6>GUATEMALA. </Tag_6>
<Tag_7>JUNIO 2007. </Tag_7>
<Tag_8>LAS CIFRAS QUE SE PRESENTAN NO HAN SIDO AUDITADAS Y TIENEN COMO FUENTE LA INFORMACION CONTABLE RECIBIDA DE LAS ENTIDADES FINANCIERAS, POR LO QUE SU VERACIDAD Y EXACTITUD , ASI COMO SUS DEFICIENCIAS, SON RESPONSABILIDAD DE LAS ENTIDADES REMITENTES. </Tag_8>
<Tag_9>SISTEMA BANCARIO. </Tag_9>
<Tag_9>SOCIEDADES FINANCIERAS PRIVADAS. </Tag_9>
<Tag_10>3. </Tag_10>
<Tag_11>1. </Tag_11>
<Tag_12>06/06/2008. </Tag_12>
</RECORD>
<RECORD>
<Tag_1>1.13. </Tag_1>
<Tag_2>ESTADISTICAS. </Tag_2>
<Tag_3>BANCOS, SEGUROS Y FINANZAS. </Tag_3>
<Tag_4>BOLETIN DE ESTADISTICAS. </Tag_4>
<Tag_5>SUPERINTENDENCIA DE BANCOS. </Tag_5>
<Tag_6>GUATEMALA. </Tag_6>
<Tag_7>OCTUBRE 2007. </Tag_7>
<Tag_8>LAS CIFRAS QUE SE PRESENTAN NO HAN SIDO AUDITADAS Y TIENEN COMO FUENTE LA INFORMACION CONTABLE RECIBIDA DE LAS ENTIDADES FINANCIERAS, POR LO QUE SU VERACIDAD Y EXACTITUD , ASI COMO SUS DEFICIENCIAS, SON RESPONSABILIDAD DE LAS ENTIDADES REMITENTES. </Tag_8>
<Tag_9>SISTEMA BANCARIO. </Tag_9>
<Tag_9>SOCIEDADES FINANCIERAS PRIVADAS. </Tag_9>
<Tag_10>3. </Tag_10>
<Tag_11>1. </Tag_11>
<Tag_12>06/06/2008. </Tag_12>
</RECORD>
<RECORD>
<Tag_1>1.14. </Tag_1>
<Tag_2>ESTADISTICAS. </Tag_2>
<Tag_3>BANCOS, SEGUROS Y FINANZAS. </Tag_3>
<Tag_4>BOLETIN DE ESTADISTICAS. </Tag_4>
<Tag_5>SUPERINTENDENCIA DE BANCOS. </Tag_5>
<Tag_6>GUATEMALA. </Tag_6>
<Tag_7>SEPTIEMBRE 2006. </Tag_7>
<Tag_8>LAS CIFRAS QUE SE PRESENTAN NO HAN SIDO AUDITADAS Y TIENEN COMO FUENTE LA INFORMACION CONTABLE RECIBIDA DE LAS ENTIDADES FINANCIERAS, POR LO QUE SU VERACIDAD Y EXACTITUD , ASI COMO SUS DEFICIENCIAS, SON RESPONSABILIDAD DE LAS ENTIDADES REMITENTES. </Tag_8>
<Tag_9>SISTEMA BANCARIO. </Tag_9>
<Tag_9>SOCIEDADES FINANCIERAS PRIVADAS. </Tag_9>
<Tag_10>3. </Tag_10>
<Tag_11>1. </Tag_11>
<Tag_12>06/06/2008. </Tag_12>
</RECORD>
<RECORD>
<Tag_1>1.15. </Tag_1>
<Tag_2>ESTADISTICAS. </Tag_2>
<Tag_3>BANCOS, SEGUROS Y FINANZAS. </Tag_3>
<Tag_4>BOLETIN DE ESTADISTICAS. </Tag_4>
<Tag_5>SUPERINTENDENCIA DE BANCOS. </Tag_5>
<Tag_6>GUATEMALA. </Tag_6>
<Tag_7>SEPTIEMBRE 2006. </Tag_7>
<Tag_8>LAS CIFRAS QUE SE PRESENTAN NO HAN SIDO AUDITADAS Y TIENEN COMO FUENTE LA INFORMACION CONTABLE RECIBIDA DE LAS ENTIDADES FINANCIERAS, POR LO QUE SU VERACIDAD Y EXACTITUD , ASI COMO SUS DEFICIENCIAS, SON RESPONSABILIDAD DE LAS ENTIDADES REMITENTES. </Tag_8>
<Tag_9>SISTEMA BANCARIO. </Tag_9>
<Tag_9>SOCIEDADES FINANCIERAS PRIVADAS. </Tag_9>
<Tag_10>3. </Tag_10>
<Tag_11>1. </Tag_11>
<Tag_12>06/06/2008. </Tag_12>
</RECORD>
<RECORD>
<Tag_1>1.16. </Tag_1>
<Tag_2>ESTADISTICAS. </Tag_2>
<Tag_3>BANCOS, SEGUROS Y FINANZAS. </Tag_3>
<Tag_4>BOLETIN DE ESTADISTICAS. </Tag_4>
<Tag_5>SUPERINTENDENCIA DE BANCOS. </Tag_5>
<Tag_6>GUATEMALA. </Tag_6>
<Tag_7>AGOSTO 2006. </Tag_7>
<Tag_8>LAS CITAS QUE SE PRESENTAN NO HAN SIDO AUDITADAS Y TIENEN COMO FUENTE LA INFORMACION CONTABLE RECIBIDA DE LAS ENTIDADES FINANCIERAS, POR LO QUE SU VERACIDAD Y EXACTITUD, ASI COMO SUS DEFICIENCIAS, SON RESPONSABILIDAD DE LAS ENTIDADES REMITENTES. </Tag_8>
<Tag_9>SISTEMA BANCARIO. </Tag_9>
<Tag_9>SOCIEDADES FINANCIERAS PRIVADAS. </Tag_9>
<Tag_10>3. </Tag_10>
<Tag_11>1. </Tag_11>
<Tag_12>09//06/2008. </Tag_12>
</RECORD>
<RECORD>
<Tag_1>1.17. </Tag_1>
<Tag_2>ESTADISTICAS. </Tag_2>
<Tag_3>BANCOS, SEGUROS Y FINANZAS. </Tag_3>
<Tag_4>BOLETIN DE ESTADISTICAS. </Tag_4>
<Tag_5>SUPERINTENDENCIA DE BANCOS. </Tag_5>
<Tag_6>GUATEMALA. </Tag_6>
<Tag_7>AGOSTO 2006. </Tag_7>
<Tag_8>LAS CITAS QUE SE PRESENTAN NO HAN SIDO AUDITADAS Y TIENEN COMO FUENTE LA INFORMACION CONTABLE RECIBIDA DE LAS ENTIDADES FINANCIERAS, POR LO QUE SU VERACIDAD Y EXACTITUD, ASI COMO SUS DEFICIENCIAS, SON RESPONSABILIDAD DE LAS ENTIDADES REMITENTES. </Tag_8>
<Tag_9>SISTEMA BANCARIO. </Tag_9>
<Tag_9>SOCIEDADES FINANCIERAS PRIVADAS. </Tag_9>
<Tag_10>3. </Tag_10>
<Tag_11>1. </Tag_11>
<Tag_12>09/06/2008. </Tag_12>
</RECORD>
<RECORD>
<Tag_1>1.18. </Tag_1>
<Tag_2>ESTADISTICAS. </Tag_2>
<Tag_3>BANCOS, SEGUROS Y FINANZAS. </Tag_3>
<Tag_4>BOLETIN DE ESTADISTICAS. </Tag_4>
<Tag_5>SUPERINTENDENCIA DE BANCOS. </Tag_5>
<Tag_6>GUATEMALA. </Tag_6>
<Tag_7>AGOSTO 2006. </Tag_7>
<Tag_8>LAS CITAS QUE SE PRESENTAN NO HAN SIDO AUDITADAS Y TIENEN COMO FUENTE LA INFORMACION CONTABLE RECIBIDA DE LAS ENTIDADES FINANCIERAS, POR LO QUE SU VERACIDAD Y EXACTITUD, ASI COMO SUS DEFICIENCIAS, SON RESPONSABILIDAD DE LAS ENTIDADES REMITENTES. </Tag_8>
<Tag_9>CASAS DE CAMBIO. </Tag_9>
<Tag_9>ALMACENES GENERALES DE DEPOSITO. </Tag_9>
<Tag_10>3. </Tag_10>
<Tag_11>1. </Tag_11>
<Tag_12>09/06/2008. </Tag_12>
</RECORD>
<RECORD>
<Tag_1>1.19. </Tag_1>
<Tag_2>ESTADISTICAS. </Tag_2>
<Tag_3>BANCOS, SEGUROS Y FINANZAS. </Tag_3>
<Tag_4>BOLETIN ANUAL DE ESTADISTICAS. </Tag_4>
<Tag_5>SUPERINTENDENCIA DE BANCOS. </Tag_5>
<Tag_6>GUATEMALA. </Tag_6>
<Tag_7>AÑO 2005. </Tag_7>
<Tag_8>LAS CITAS QUE SE PRESENTAN NO HAN SIDO AUDITADAS Y TIENEN COMO FUENTE LA INFORMACION CONTABLE RECIBIDA DE LAS ENTIDADES FINANCIERAS, POR LO QUE SU VERACIDAD Y EXACTITUD, ASI COMO SUS DEFICIENCIAS, SON RESPONSABILIDAD DE LAS ENTIDADES REMITENTES. </Tag_8>
<Tag_9>BANCOS NACIONALES. </Tag_9>
<Tag_9>BANCOS EXTRANJEROS. </Tag_9>
<Tag_10>3. </Tag_10>
<Tag_11>1. </Tag_11>
<Tag_12>09/06/2008. </Tag_12>
</RECORD>
<RECORD>
<Tag_1>1.20. </Tag_1>
<Tag_2>ESTADISTICAS. </Tag_2>
<Tag_3>BANCOS, SEGUROS Y FINANZAS. </Tag_3>
<Tag_4>BOLETIN DE ESTADISTICAS. </Tag_4>
<Tag_5>SUPERINTENDENCIA DE BANCOS. </Tag_5>
<Tag_6>GUATEMALA. </Tag_6>
<Tag_7>ABRIL 2007. </Tag_7>
<Tag_8>LAS CITAS QUE SE PRESENTAN NO HAN SIDO AUDITADAS Y TIENEN COMO FUENTE LA INFORMACION CONTABLE RECIBIDA DE LAS ENTIDADES FINANCIERAS, POR LO QUE SU VERACIDAD Y EXACTITUD, ASI COMO SUS DEFICIENCIAS, SON RESPONSABILIDAD DE LAS ENTIDADES REMITENTES. </Tag_8>
<Tag_9>SOCIEDADES FINANCIERAS PRIVADAS. </Tag_9>
<Tag_9>CASAS DE CAMBIO. </Tag_9>
<Tag_10>3. </Tag_10>
<Tag_11>1. </Tag_11>
<Tag_12>09/06/2008. </Tag_12>
</RECORD>
<RECORD>
<Tag_1>1.21. </Tag_1>
<Tag_2>ESTADISTICAS. </Tag_2>
<Tag_3>BANCOS, SEGUROS Y FINANZAS. </Tag_3>
<Tag_4>BOLETIN DE ESTADISTICAS. </Tag_4>
<Tag_5>SUPERINTENDENCIA DE BANCOS. </Tag_5>
<Tag_6>GUATEMALA. </Tag_6>
<Tag_7>OCTUBRE 2005. </Tag_7>
<Tag_8>LAS CITAS QUE SE PRESENTAN NO HAN SIDO AUDITADAS Y TIENEN COMO FUENTE LA INFORMACION CONTABLE RECIBIDA DE LAS ENTIDADES FINANCIERAS, POR LO QUE SU VERACIDAD Y EXACTITUD, ASI COMO SUS DEFICIENCIAS, SON RESPONSABILIDAD DE LAS ENTIDADES REMITENTES. </Tag_8>
<Tag_9>CASAS DE CAMBIO. </Tag_9>
<Tag_9>ALMACENES GENERALES DE DEPOSITO. </Tag_9>
<Tag_10>3. </Tag_10>
<Tag_11>1. </Tag_11>
<Tag_12>09/06/2008. </Tag_12>
</RECORD>
<RECORD>
<Tag_1>1.22. </Tag_1>
<Tag_2>ESTADISTICAS. </Tag_2>
<Tag_3>BANCOS, SEGUROS Y FINANZAS. </Tag_3>
<Tag_4>BOLETIN ANUAL DE ESTADISTICAS. </Tag_4>
<Tag_5>SUPERINTENDENCIA DE BANCOS. </Tag_5>
<Tag_6>GUATEMALA. </Tag_6>
<Tag_7>AÑO 2006. </Tag_7>
<Tag_8>LAS CITAS QUE SE PRESENTAN NO HAN SIDO AUDITADAS Y TIENEN COMO FUENTE LA INFORMACION CONTABLE RECIBIDA DE LAS ENTIDADES FINANCIERAS, POR LO QUE SU VERACIDAD Y EXACTITUD, ASI COMO SUS DEFICIENCIAS, SON RESPONSABILIDAD DE LAS ENTIDADES REMITENTES. </Tag_8>
<Tag_9>EMPRESAS DE SEGUROS. </Tag_9>
<Tag_9>EMPRESAS DE FIANZAS. </Tag_9>
<Tag_10>3. </Tag_10>
<Tag_11>1. </Tag_11>
<Tag_12>09/06/2008. </Tag_12>
</RECORD>
<RECORD>
<Tag_1>1.23. </Tag_1>
<Tag_2>ESTADISTICAS. </Tag_2>
<Tag_3>BANCOS, SEGUROS Y FINANZAS. </Tag_3>
<Tag_4>BOLETIN TRIMESTRAL DE ESTADISTICAS. </Tag_4>
<Tag_5>SUPERINTENDENCIA DE BANCOS. </Tag_5>
<Tag_6>GUATEMALA. </Tag_6>
<Tag_7>DICIEMBRE 2006. </Tag_7>
<Tag_8>LAS CITAS QUE SE PRESENTAN NO HAN SIDO AUDITADAS Y TIENEN COMO FUENTE LA INFORMACION CONTABLE RECIBIDA DE LAS ENTIDADES FINANCIERAS, POR LO QUE SU VERACIDAD Y EXACTITUD, ASI COMO SUS DEFICIENCIAS, SON RESPONSABILIDAD DE LAS ENTIDADES REMITENTES. </Tag_8>
<Tag_9>EMPRESAS DE SEGUROS. </Tag_9>
<Tag_9>EMPRESAS DE FIANZAS. </Tag_9>
<Tag_10>3. </Tag_10>
<Tag_11>1. </Tag_11>
<Tag_12>09/06/2008. </Tag_12>
</RECORD>
<RECORD>
<Tag_1>1.24. </Tag_1>
<Tag_2>ESTADISTICAS. </Tag_2>
<Tag_3>BANCOS, SEGUROS Y FIANZAS. </Tag_3>
<Tag_4>BOLETIN DE ESTADISTICAS. </Tag_4>
<Tag_5>SUPERINTENDENCIA DE BANCOS. </Tag_5>
<Tag_6>GUATEMALA. </Tag_6>
<Tag_7>OCTUBRE 2006. </Tag_7>
<Tag_8>LAS CITAS QUE SE PRESENTAN NO HAN SIDO AUDITADAS Y TIENEN COMO FUENTE LA INFORMACION CONTABLE RECIBIDA DE LAS ENTIDADES FINANCIERAS, POR LO QUE SU VERACIDAD Y EXACTITUD, ASI COMO SUS DEFICIENCIAS, SON RESPONSABILIDAD DE LAS ENTIDADES REMITENTES. </Tag_8>
<Tag_9>SISTEMA BANCARIO. </Tag_9>
<Tag_9>CASAS DE CAMBIO. </Tag_9>
<Tag_10>3. </Tag_10>
<Tag_11>1. </Tag_11>
<Tag_12>09/06/2008. </Tag_12>
</RECORD>
<RECORD>
<Tag_1>1.25. </Tag_1>
<Tag_2>ESTADISTICAS. </Tag_2>
<Tag_3>BANCOS, SEGUROS Y FIANZAS. </Tag_3>
<Tag_4>BOLETIN TRIMESTRAL DE ESTADISTICAS. </Tag_4>
<Tag_5>SUPERINTENDENCIA DE BANCOS. </Tag_5>
<Tag_6>GUATEMALA. </Tag_6>
<Tag_7>SEPTIEMBRE 2006. </Tag_7>
<Tag_8>LAS CITAS QUE SE PRESENTAN NO HAN SIDO AUDITADAS Y TIENEN COMO FUENTE LA INFORMACION CONTABLE RECIBIDA DE LAS ENTIDADES FINANCIERAS, POR LO QUE SU VERACIDAD Y EXACTITUD, ASI COMO SUS DEFICIENCIAS, SON RESPONSABILIDAD DE LAS ENTIDADES REMITENTES. </Tag_8>
<Tag_9>EMPRESAS DE SEGUROS. </Tag_9>
<Tag_9>EMPRESAS DE FIANZAS. </Tag_9>
<Tag_10>3. </Tag_10>
<Tag_11>1. </Tag_11>
<Tag_12>09/06/2008. </Tag_12>
</RECORD>
<RECORD>
<Tag_1>1.26. </Tag_1>
<Tag_2>ESTADISTICAS. </Tag_2>
<Tag_3>BANCOS, SEGUROS Y FINANZAS. </Tag_3>
<Tag_4>BOLETIN DE ESTADISTICAS. </Tag_4>
<Tag_5>SUPERINTENDENCIA DE BANCOS. </Tag_5>
<Tag_6>GUATEMALA. </Tag_6>
<Tag_7>FEBRERO 2007. </Tag_7>
<Tag_8>LAS CIFRAS QUE SE PRESENTAN NO HAN SIDO AUDITADAS Y TIENEN COMO FUENTE LA INFORMACION CONTABLE RECIBIDA DE LAS ENTIDADES FINANCIERAS, POR LO QUE SU VERACIDAD Y EXACTITUD, ASI COMO SUS DEFICIENCIAS, SON RESPONSABILIDAD DE LAS ENTIDADES REMITENTES. </Tag_8>
<Tag_9>SISTEMA BANCARIO. </Tag_9>
<Tag_9>SOCIEDADES FINANCIERAS PRIVADAS. </Tag_9>
<Tag_10>3. </Tag_10>
<Tag_11>1. </Tag_11>
<Tag_12>09/06/2008. </Tag_12>
</RECORD>
<RECORD>
<Tag_1>1.27. </Tag_1>
<Tag_2>ESTADISTICAS. </Tag_2>
<Tag_3>BANCOS, SEGUROS Y FINANZAS. </Tag_3>
<Tag_4>BOLETIN DE ESTADISTICAS. </Tag_4>
<Tag_5>SUPERINTENDENCIA DE BANCOS. </Tag_5>
<Tag_6>GUATEMALA. </Tag_6>
<Tag_7>MAYO 2007. </Tag_7>
<Tag_8>LAS CIFRAS QUE SE PRESENTAN NO HAN SIDO AUDITADAS Y TIENEN COMO FUENTE LA INFORMACION CONTABLE RECIBIDA DE LAS ENTIDADES FINANCIERAS, POR LO QUE SU VERACIDAD Y EXACTITUD, ASI COMO SUS DEFICIENCIAS, SON RESPONSABILIDAD DE LAS ENTIDADES REMITENTES. </Tag_8>
<Tag_9>CASAS DE CAMBIO. </Tag_9>
<Tag_9>ALMACENES GENERALES DE DEPOSITO. </Tag_9>
<Tag_10>3. </Tag_10>
<Tag_11>1. </Tag_11>
<Tag_12>09/06/2008. </Tag_12>
</RECORD>
<RECORD>
<Tag_1>1.28. </Tag_1>
<Tag_2>ESTADISTICAS. </Tag_2>
<Tag_3>BANCOS, SEGUROS Y FINANZAS. </Tag_3>
<Tag_4>BOLETIN TRIMESTRAL DE ESTADISTICAS. </Tag_4>
<Tag_5>SUPERINTENDENCIA DE BANCOS. </Tag_5>
<Tag_6>GUATEMALA. </Tag_6>
<Tag_7>MARZO 2007. </Tag_7>
<Tag_8>LAS CIFRAS QUE SE PRESENTAN NO HAN SIDO AUDITADAS Y TIENEN COMO FUENTE LA INFORMACION CONTABLE RECIBIDA DE LAS ENTIDADES FINANCIERAS, POR LO QUE SU VERACIDAD Y EXACTITUD, ASI COMO SUS DEFICIENCIAS, SON RESPONSABILIDAD DE LAS ENTIDADES REMITENTES. </Tag_8>
<Tag_9>EMPRESAS DE SEGUROS. </Tag_9>
<Tag_9>EMPRESAS DE FIANZAS. </Tag_9>
<Tag_10>3. </Tag_10>
<Tag_11>1. </Tag_11>
<Tag_12>09/06/2008. </Tag_12>
</RECORD>
<RECORD>
<Tag_1>1.29. </Tag_1>
<Tag_2>ESTADISTICAS. </Tag_2>
<Tag_3>BANCOS, SEGUROS Y FINANZAS. </Tag_3>
<Tag_4>BOLETIN DE ESTADISTICAS. </Tag_4>
<Tag_5>SUPERINTENDENCIA DE BANCOS. </Tag_5>
<Tag_6>GUATEMALA. </Tag_6>
<Tag_7>DICIEMBRE 2006. </Tag_7>
<Tag_8>LAS CIFRAS QUE SE PRESENTAN NO HAN SIDO AUDITADAS Y TIENEN COMO FUENTE LA INFORMACION CONTABLE RECIBIDA DE LAS ENTIDADES FINANCIERAS, POR LO QUE SU VERACIDAD Y EXACTITUD, ASI COMO SUS DEFICIENCIAS, SON RESPONSABILIDAD DE LAS ENTIDADES REMITENTES. </Tag_8>
<Tag_9>SISTEMA BANCARIO. </Tag_9>
<Tag_9>CASAS DE CAMBIO. </Tag_9>
<Tag_10>3. </Tag_10>
<Tag_11>1. </Tag_11>
<Tag_12>09/06/2008. </Tag_12>
</RECORD>
<RECORD>
<Tag_1>1.30. </Tag_1>
<Tag_2>ESTADISTICAS. </Tag_2>
<Tag_3>BANCOS, SEGUROS FINANZAS. </Tag_3>
<Tag_4>BOLETIN DE ESTADISTICAS. </Tag_4>
<Tag_5>SUPERINTENDENCIA DE BANCOS. </Tag_5>
<Tag_6>GUATEMALA. </Tag_6>
<Tag_7>JUNIO 2007. </Tag_7>
<Tag_8>LAS CIFRAS QUE SE PRESENTAN NO HAN SIDO AUDITADAS Y TIENEN COMO FUENTE LA INFORMACION CONTABLE RECIBIDA DE LAS ENTIDADES FINANCIERAS, POR LO QUE SU VERACIDAD Y EXACTITUD, ASI COMO SUS DEFICIENCIAS, SON RESPONSABILIDAD DE LAS ENTIDADES REMITENTES. </Tag_8>
<Tag_9>BANCO DE GUATEMALA. </Tag_9>
<Tag_9>CASAS DE CAMBIO. </Tag_9>
<Tag_10>3. </Tag_10>
<Tag_11>1. </Tag_11>
<Tag_12>09/06/2008. </Tag_12>
</RECORD>
<RECORD>
<Tag_1>1.31. </Tag_1>
<Tag_2>ESTADISTICAS. </Tag_2>
<Tag_3>BANCOS, SEGUROS Y FINANZAS. </Tag_3>
<Tag_4>BOLETIN TRIMESTRAL DE ESTADISTICAS. </Tag_4>
<Tag_5>SUPERINTENDENCIA DE BANCOS. </Tag_5>
<Tag_6>GUATEMALA. </Tag_6>
<Tag_7>JUNIO 2007. </Tag_7>
<Tag_8>LAS CIFRAS QUE SE PRESENTAN NO HAN SIDO AUDITADAS Y TIENEN COMO FUENTE LA INFORMACION CONTABLE RECIBIDA DE LAS ENTIDADES FINANCIERAS, POR LO QUE SU VERACIDAD Y EXACTITUD, ASI COMO SUS DEFICIENCIAS, SON RESPONSABILIDAD DE LAS ENTIDADES REMITENTES. </Tag_8>
<Tag_9>EMPRESAS DE SEGUROS. </Tag_9>
<Tag_9>EMPRESAS DE FIANZAS. </Tag_9>
<Tag_10>3. </Tag_10>
<Tag_11>1. </Tag_11>
<Tag_12>09/06/2008. </Tag_12>
</RECORD>
<RECORD>
<Tag_1>1.32. </Tag_1>
<Tag_2>ESTADISTICAS. </Tag_2>
<Tag_3>BANCOS, SEGUROS Y FINANZAS. </Tag_3>
<Tag_4>BOLETIN TRIMESTRAL DE ESTADISTICAS. </Tag_4>
<Tag_5>SUPERINTENDENCIA DE BANCOS. </Tag_5>
<Tag_6>GUATEMALA. </Tag_6>
<Tag_7>SEPTIEMBRE 2005. </Tag_7>
<Tag_8>LAS CIFRAS QUE SE PRESENTAN NO HAN SIDO AUDITADAS Y TIENEN COMO FUENTE LA INFORMACION CONTABLE RECIBIDA DE LAS ENTIDADES FINANCIERAS, POR LO QUE SU VERACIDAD Y EXACTITUD, ASI COMO SUS DEFICIENCIAS, SON RESPONSABILIDAD DE LAS ENTIDADES REMITENTES. </Tag_8>
<Tag_9>EMPRESAS DE SEGUROS. </Tag_9>
<Tag_9>EMPRESAS DE FIANZAS. </Tag_9>
<Tag_10>3. </Tag_10>
<Tag_11>1. </Tag_11>
<Tag_12>09/06/2008. </Tag_12>
</RECORD>
<RECORD>
<Tag_1>1.33. </Tag_1>
<Tag_2>ESTADISTICAS. </Tag_2>
<Tag_3>BANCOS, SEGUROS Y FINANZAS. </Tag_3>
<Tag_4>BOLETIN DE ESTADISTICAS. </Tag_4>
<Tag_5>SUPERINTENDENCIA DE BANCOS. </Tag_5>
<Tag_6>GUATEMALA. </Tag_6>
<Tag_7>OCTUBRE 2005. </Tag_7>
<Tag_8>LAS CIFRAS QUE SE PRESENTAN NO HAN SIDO AUDITADAS Y TIENEN COMO FUENTE LA INFORMACION CONTABLE RECIBIDA DE LAS ENTIDADES FINANCIERAS, POR LO QUE SU VERACIDAD Y EXACTITUD, ASI COMO SUS DEFICIENCIAS, SON RESPONSABILIDAD DE LAS ENTIDADES REMITENTES. </Tag_8>
<Tag_9>SISTEMA BANCARIO. </Tag_9>
<Tag_9>SOCIEDADES FINANCIERAS PRIVADAS. </Tag_9>
<Tag_10>3. </Tag_10>
<Tag_11>1. </Tag_11>
<Tag_12>09/06/2008. </Tag_12>
</RECORD>
<RECORD>
<Tag_1>1.34. </Tag_1>
<Tag_2>ESTADISTICAS. </Tag_2>
<Tag_3>BANCOS, SEGUROS Y FINANZAS. </Tag_3>
<Tag_4>BOLETIN DE ESTADISTICAS. </Tag_4>
<Tag_5>SUPERINTENDENCIA DE BANCOS. </Tag_5>
<Tag_6>GUATEMALA. </Tag_6>
<Tag_7>AGOSTO 2006. </Tag_7>
<Tag_8>LAS CIFRAS QUE SE PRESENTAN NO HAN SIDO AUDITADAS Y TIENEN COMO FUENTE LA INFORMACION CONTABLE RECIBIDA DE LAS ENTIDADES FINANCIERAS, POR LO QUE SU VERACIDAD Y EXACTITUD, ASI COMO SUS DEFICIENCIAS, SON RESPONSABILIDAD DE LAS ENTIDADES REMITENTES. </Tag_8>
<Tag_9>SOCIEDADES FINANCIERAS PRIVADAS. </Tag_9>
<Tag_9>CASAS DE CAMBIO. </Tag_9>
<Tag_10>3. </Tag_10>
<Tag_11>1. </Tag_11>
<Tag_12>09/06/2008. </Tag_12>
</RECORD>
<RECORD>
<Tag_1>1.35. </Tag_1>
<Tag_2>ESTADISTICAS. </Tag_2>
<Tag_3>BANCOS, SEGUROS Y FINANZAS. </Tag_3>
<Tag_4>BOLETIN DE ESTADISTICAS. </Tag_4>
<Tag_5>SUPERINTENDENCIA DE BANCOS. </Tag_5>
<Tag_6>GUATEMALA. </Tag_6>
<Tag_7>NOVIEMBRE 2006. </Tag_7>
<Tag_8>LAS CIFRAS QUE SE PRESENTAN NO HAN SIDO AUDITADAS Y TIENEN COMO FUENTE LA INFORMACION CONTABLE RECIBIDA DE LAS ENTIDADES FINANCIERAS, POR LO QUE SU VERACIDAD Y EXACTITUD, ASI COMO SUS DEFICIENCIAS, SON RESPONSABILIDAD DE LAS ENTIDADES REMITENTES. </Tag_8>
<Tag_9>SISTEMA BANCARIO. </Tag_9>
<Tag_9>ALMACENES GENERALES DE DEPOSITO. </Tag_9>
<Tag_10>3. </Tag_10>
<Tag_11>1. </Tag_11>
<Tag_12>09/06/2008. </Tag_12>
</RECORD>
<RECORD>
<Tag_1>1.36. </Tag_1>
<Tag_2>ESTADISTICAS. </Tag_2>
<Tag_3>BANCOS, SEGUROS Y FINANZAS. </Tag_3>
<Tag_4>BOLETIN DE ESTADISTICAS. </Tag_4>
<Tag_5>SUPERINTENDENCIA DE BANCOS. </Tag_5>
<Tag_6>GUATEMALA. </Tag_6>
<Tag_7>NOVIEMBRE 2006. </Tag_7>
<Tag_8>LAS CIFRAS QUE SE PRESENTAN NO HAN SIDO AUDITADAS Y TIENEN COMO FUENTE LA INFORMACION CONTABLE RECIBIDA DE LAS ENTIDADES FINANCIERAS, POR LO QUE SU VERACIDAD Y EXACTITUD, ASI COMO SUS DEFICIENCIAS, SON RESPONSABILIDAD DE LAS ENTIDADES REMITENTES. </Tag_8>
<Tag_9>SISTEMA BANCARIO. </Tag_9>
<Tag_9>CASAS DE CAMBIO. </Tag_9>
<Tag_10>3. </Tag_10>
<Tag_11>1. </Tag_11>
<Tag_12>09/06/2008. </Tag_12>
</RECORD>
<RECORD>
<Tag_1>1.37. </Tag_1>
<Tag_2>ESTADISTICAS. </Tag_2>
<Tag_3>BANCOS, SEGUROS Y FINANZAS. </Tag_3>
<Tag_4>BOLETIN DE ESTADISTICAS. </Tag_4>
<Tag_5>SUPERINTENDENCIA DE BANCOS. </Tag_5>
<Tag_6>GUATEMALA. </Tag_6>
<Tag_7>JULIO 2006. </Tag_7>
<Tag_8>LAS CIFRAS QUE SE PRESENTAN NO HAN SIDO AUDITADAS Y TIENEN COMO FUENTE LA INFORMACION CONTABLE RECIBIDA DE LAS ENTIDADES FINANCIERAS, POR LO QUE SU VERACIDAD Y EXACTITUD, ASI COMO SUS DEFICIENCIAS, SON RESPONSABILIDAD DE LAS ENTIDADES REMITENTES. </Tag_8>
<Tag_9>SISTEMA BANCARIO. </Tag_9>
<Tag_9>CASAS DE CAMBIO. </Tag_9>
<Tag_10>3. </Tag_10>
<Tag_11>1. </Tag_11>
<Tag_12>09/06/2008. </Tag_12>
</RECORD>
<RECORD>
<Tag_1>1.38. </Tag_1>
<Tag_2>ESTADISTICAS. </Tag_2>
<Tag_3>BANCOS, SEGUROS Y FINANZAS. </Tag_3>
<Tag_4>BOLETIN DE ESTADISTICAS. </Tag_4>
<Tag_5>SUPERINTENDENCIA DE BANCOS. </Tag_5>
<Tag_6>GUATEMALA. </Tag_6>
<Tag_7>MAYO 2007. </Tag_7>
<Tag_8>LAS CIFRAS QUE SE PRESENTAN NO HAN SIDO AUDITADAS Y TIENEN COMO FUENTE LA INFORMACION CONTABLE RECIBIDA DE LAS ENTIDADES FINANCIERAS, POR LO QUE SU VERACIDAD Y EXACTITUD, ASI COMO SUS DEFICIENCIAS, SON RESPONSABILIDAD DE LAS ENTIDADES REMITENTES. </Tag_8>
<Tag_9>CASAS DE CAMBIO. </Tag_9>
<Tag_9>ALMACENES GENERALES DE DEPOSITO. </Tag_9>
<Tag_10>3. </Tag_10>
<Tag_11>1. </Tag_11>
<Tag_12>09/06/2008. </Tag_12>
</RECORD>
<RECORD>
<Tag_1>1.39. </Tag_1>
<Tag_2>ESTADISTICAS. </Tag_2>
<Tag_3>BANCOS, SEGUROS Y FINANZAS. </Tag_3>
<Tag_4>BOLETIN TRIMESTRAL DE ESTADISTICAS. </Tag_4>
<Tag_5>SUPERINTENDENCIA DE BANCOS. </Tag_5>
<Tag_6>GUATEMALA. </Tag_6>
<Tag_7>MARZO 2007. </Tag_7>
<Tag_8>LAS CIFRAS QUE SE PRESENTAN NO HAN SIDO AUDITADAS Y TIENEN COMO FUENTE LA INFORMACION CONTABLE RECIBIDA DE LAS ENTIDADES FINANCIERAS, POR LO QUE SU VERACIDAD Y EXACTITUD, ASI COMO SUS DEFICIENCIAS, SON RESPONSABILIDAD DE LAS ENTIDADES REMITENTES. </Tag_8>
<Tag_9>EMPRESAS DE SEGUROS. </Tag_9>
<Tag_9>EMPRESAS DE FIANZAS. </Tag_9>
<Tag_10>3. </Tag_10>
<Tag_11>1. </Tag_11>
<Tag_12>09/06/2008. </Tag_12>
</RECORD>
<RECORD>
<Tag_1>1.40. </Tag_1>
<Tag_2>ESTADISTICAS. </Tag_2>
<Tag_3>BANCOS, SEGUROS Y FIANZAS. </Tag_3>
<Tag_4>BOLETIN DE ESTADISTICAS. </Tag_4>
<Tag_5>SUPERINTENDENCIA DE BANCOS. </Tag_5>
<Tag_6>GUATEMALA. </Tag_6>
<Tag_7>ENERO 2007. </Tag_7>
<Tag_8>LAS CIFRAS QUE SE PRESENTAN NO HAN SIDO AUDITADAS Y TIENEN COMO FUENTE LA INFORMACION CONTABLE RECIBIDA DE LAS ENTIDADES FINANCIERAS, POR LO QUE SU VERACIDAD Y EXACTITUD, ASI COMO SUS DEFICIENCIAS, SON RESPONSABILIDAD DE LAS ENTIDADES REMITENTES. </Tag_8>
<Tag_9>SISTEMA BANCARIO. </Tag_9>
<Tag_9>SOCIEDADES FINANCIERAS PRIVADAS. </Tag_9>
<Tag_10>3. </Tag_10>
<Tag_11>1. </Tag_11>
<Tag_12>09/06/2008. </Tag_12>
</RECORD>
<RECORD>
<Tag_1>1.41. </Tag_1>
<Tag_2>ESTADISTICAS. </Tag_2>
<Tag_3>BANCOS, SEGUROS Y FINANZAS. </Tag_3>
<Tag_4>BOLETIN ANUAL DE ESTADISTICAS. </Tag_4>
<Tag_5>SUPERINTENDENCIA DE BANCOS. </Tag_5>
<Tag_6>GUATEMALA. </Tag_6>
<Tag_7>AÑO 2006. </Tag_7>
<Tag_8>LAS CIFRAS QUE SE PRESENTAN NO HAN SIDO AUDITADAS Y TIENEN COMO FUENTE LA INFORMACION CONTABLE RECIBIDA DE LAS ENTIDADES FINANCIERAS, POR LO QUE SU VERACIDAD Y EXACTITUD, ASI COMO SUS DEFICIENCIAS, SON RESPONSABILIDAD DE LAS ENTIDADES REMITENTES. </Tag_8>
<Tag_9>EMPRESAS DE SEGUROS. </Tag_9>
<Tag_9>INSTITUTO DE FOMENTO DE HIPOTECAS ASEGURADAS. </Tag_9>
<Tag_10>3. </Tag_10>
<Tag_11>1. </Tag_11>
<Tag_12>10/06/2008. </Tag_12>
</RECORD>
<RECORD>
<Tag_1>1.42. </Tag_1>
<Tag_2>ESTADISTICAS. </Tag_2>
<Tag_3>BANCOS, SEGUROS Y FINANZAS. </Tag_3>
<Tag_4>BOLETIN DE ESTADISTICAS. </Tag_4>
<Tag_5>SUPERINTENDENCIA DE BANCOS. </Tag_5>
<Tag_6>GUATEMALA. </Tag_6>
<Tag_7>JULIO 2007. </Tag_7>
<Tag_8>LAS CIFRAS QUE SE PRESENTAN NO HAN SIDO AUDITADAS Y TIENEN COMO FUENTE LA INFORMACION CONTABLE RECIBIDA DE LAS ENTIDADES FINANCIERAS, POR LO QUE SU VERACIDAD Y EXACTITUD, ASI COMO SUS DEFICIENCIAS, SON RESPONSABILIDAD DE LAS ENTIDADES REMITENTES. </Tag_8>
<Tag_9>CASAS DE CAMBIO. </Tag_9>
<Tag_9>ALMACENES GENERALES DE DEPOSITO. </Tag_9>
<Tag_10>3. </Tag_10>
<Tag_11>1. </Tag_11>
<Tag_12>10/06/2008. </Tag_12>
</RECORD>
<RECORD>
<Tag_1>1.43. </Tag_1>
<Tag_2>ESTADISTICAS. </Tag_2>
<Tag_3>BANCOS, SEGUROS Y FINANZAS. </Tag_3>
<Tag_4>BOLETIN DE ESTADISTICAS. </Tag_4>
<Tag_5>SUPERINTENDENCIA DE BANCOS. </Tag_5>
<Tag_6>GUATEMALA. </Tag_6>
<Tag_7>JULIO 2007. </Tag_7>
<Tag_8>LAS CIFRAS QUE SE PRESENTAN NO HAN SIDO AUDITADAS Y TIENEN COMO FUENTE LA INFORMACION CONTABLE RECIBIDA DE LAS ENTIDADES FINANCIERAS, POR LO QUE SU VERACIDAD Y EXACTITUD, ASI COMO SUS DEFICIENCIAS, SON RESPONSABILIDAD DE LAS ENTIDADES REMITENTES. </Tag_8>
<Tag_9>SISTEMA BANCARIO. </Tag_9>
<Tag_9>SOCIEDADES FINANCIERAS PRIVADAS. </Tag_9>
<Tag_10>3. </Tag_10>
<Tag_11>1. </Tag_11>
<Tag_12>10/06/2008. </Tag_12>
</RECORD>
<RECORD>
<Tag_1>1.44. </Tag_1>
<Tag_2>ESTADISTICAS. </Tag_2>
<Tag_3>BANCOS, SEGUROS Y FINANZAS. </Tag_3>
<Tag_4>BOLETIN DE ESTADISTICAS. </Tag_4>
<Tag_5>SUPERINTENDENCIA DE BANCOS. </Tag_5>
<Tag_6>GUATEMALA. </Tag_6>
<Tag_7>AGOSTO 2007. </Tag_7>